# Generated by Django 5.2.8 on 2025-11-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='drivers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rides',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
